### PR TITLE
[Fix] Video replays instead of going to next one if midroll loads after video ended

### PR DESCRIPTION
**Pull request by ntshcalleia**

### CODE REVIEW

**Review by sambua — CHANGES_REQUESTED** [review]
The way how you can reproduce it: 
/static/demos/embed/test-player.html?ad=vmap&blk=1&flt=0&ap=1&stk=1&os=0&nextwidget=true
After post roll, the same video will be played.

**Comment by ntshcalleia** [comment]
Hi @sambua, I tested a few times and couldn't reproduce the issue with those settings. I tested before and after implementing the changes from this PR. Will try again on Monday.
Also, please try with adsposition. The issue we're having is coming from scheduled midrolls.

**Comment by sambua** [comment]
Hi @ntshcalleia , the main point in the URL above is `ad=vmap` it happening on VMAP examples (https://github.com/betajs/betajs-media-components/blob/master/demos/assets/options.js#L40). You can see that midroll plays as preroll of the next video. Also trouble which had not switch to the next video still exists. It's not infinitely replay in my side but, play one video twice each time.

**Comment by ntshcalleia** [comment]
I'm able to reproduce it consistently now, thanks! Fixing it.

**Review by sambua — APPROVED** [review]

**Pull request merged**
