### PR TITLE
Feature/show companion ad in the sidebar

### PR DESCRIPTION
**Pull request by sambua**

### CODE REVIEW

**Comment by ntshcalleia** [comment]
Hi @sambua, I fixed the sticky issue + a few other minor things that I noticed. When you have the time can you please take a look at the changes and let me know if I can merge them?

**Review by ntshcalleia — APPROVED** [review]

**Review by sambua — COMMENTED** [review]
Hi @ntshcalleia , changes are great, not sticky works as expected. Only issue I'm facing is that IMA SDK skip button not showing correctly.

**Comment by sambua** [comment]
Also, will be better to fix, if floating player is shown at first on sticky option, after container player size also becomes the same as floating player size, I think we can make for it different task.

**Comment by ntshcalleia** [comment]
> Also, will be better to fix, if floating player is shown at first on sticky option, after container player size also becomes the same as floating player size, I think we can make for it different task.

That's a problem. 😬 @Bane-D can you create a bug task for fixing this?

**Comment by ntshcalleia** [comment]
> Hi @ntshcalleia , changes are great, not sticky works as expected. Only issue I'm facing is that IMA SDK skip button not showing correctly.

Can you post a screenshot of how it looks?

**Comment by sambua** [comment]
@ntshcalleia here's screenshot
Screenshot 2023-08-22 at 17 17 08

**Comment by sambua** [comment]
Also before there was companion ads showing in the desktop floating player.

**Comment by ntshcalleia** [comment]
Thanks for the demo url (and for creating that demo page, it's very helpful)! 🙂
I'm looking into it...

**Pull request merged**
