### PR TITLE
[Fix] Floating sidebar sizing

### PR DESCRIPTION
**Pull request by ntshcalleia**

### CODE REVIEW

**Review by oliverfriedmann — APPROVED** [review]
Looks good

**Comment by ntshcalleia** [comment]
Hi @sambua, thanks for the feedback! Can you check again?

**Comment by sambua** [comment]
Hi @ntshcalleia seems, all looks great now.

**Review by sambua — APPROVED** [review]

**Review by sambua — CHANGES_REQUESTED** [review]
@ntshcalleia just mentioned one trouble on hidding skip initial button and title on ads via settings: ad=1&blk=1&si=1&os=0&ap=1&ac=1&stk=0&sbr=1&flt=1&cmp=0

Attaching an image: 
Screenshot 2023-09-24 at 00 09 40

**Pull request merged**
