### PR TITLE
[Feature] Video player dataset properties

### PR DESCRIPTION
**Pull request by ntshcalleia**

### CODE REVIEW

**Review by sambua — APPROVED** [review]
All works perfect. 

Only quarter seems related only to the player itself and it sets first quarter even player not started and preroll ad is playing. I think it can confuse. We can use data-ads with quarters or set null querter while player not starts. Not sure if it could be useful apply for the ads as well.

**Comment by ntshcalleia** [comment]
Hi @sambua, thanks for the feedback! I think we're actually more interested on ads quartiles than video quartiles, so it's important we track it properly. 😄
Thanks for the tips, will fix it. 🙂

**Comment by Bane-D** [comment]
Hi Natasha, I'll focus my review about the values you added than the code itself since Rashad and Oliver are going to provide much better info there :) 

1. orientation - Love that you added "square" as well, did not think of that one and it would really cover all bases
2. for visibility I believe that we are going to be pulling the value from the "second key" called view_type, so "float", "default" and "out_of_view". Is the line 478 an error then or would we also have "floating" as a state as well? Also can we add another state to let us know that we are looking at the recommended videos? It would help in case we need to change something on that screen or remove the change when switching over.
3. adsplaying - looks like it is going to be true or false, if so, can we change it to also have a third state. It can be null, 0 or anything that we can use to detect with CSS that the ad is not set up at all. For example we could make the player have a red border and immediately tell if it is off or not (this would be useful mostly for when working on the inspection tool or when inspecting the player on page)

**Comment by ntshcalleia** [comment]
Hi @Bane-D, sorry for forgetting to reply! 😬 When I do that, please send me a reminder like you did on JIRA. 🙂

> Is the line 478 an error then or would we also have "floating" as a state as well? 

"floating" doesn't exist, good catch. 🙂 

> Also can we add another state to let us know that we are looking at the recommended videos?

This is something that's only available on Kargo side, will add it there.

> adsplaying - looks like it is going to be true or false, if so, can we change it to also have a third state. It can be null, 0 or anything that we can use to detect with CSS that the ad is not set up at all. For example we could make the player have a red border and immediately tell if it is off or not (this would be useful mostly for when working on the inspection tool or when inspecting the player on page)

What do you consider the ad not being set up? There's no configuration on the player for displaying ads? We can do that, but I'll need to override it on Kargo side since we have different configurations for setting up ads there.

**Review by Bane-D — APPROVED** [review]
Hi Natasha,

Everything looks good to me, thank you :)

**Pull request merged**
