### PR TITLE
Fix/sidebar thumb position after ads completed

### PR DESCRIPTION
**Pull request by sambua**

### CODE REVIEW

**Review by ntshcalleia — COMMENTED** [review]
Hi @sambua, works great! There's only one minor issue that's bugging me, when I scroll the video gallery and then resize the player, instead of remaining on the current position the gallery scrolls back to the next video position.

**Steps to reproduce:**
- Pause player
- Scroll to end of gallery
- Resize the player

**Current behavior:**
- Sidebar gallery scrolls back to second video

**Expected behavior:**
- Sidebar gallery stays at the position I scrolled to

**Comment by sambua** [comment]
Hi @ntshcalleia , now I've made prevent scrolling on resizing. It will not scroll at all.

**Comment by ntshcalleia** [comment]
Hi @sambua, it looks nicer now, thank you! 🙂 Can you do the same when switching floating state? When going from floating to inline it always scrolls a little bit (even when I don't move the video list). If you think it'll take a long time we can do it in a separate ticket.

**Comment by sambua** [comment]
hi @sambua I've made it to scroll to position for the next video when user changed floating and fullscreen changes. Now I've removed them

**Comment by ntshcalleia** [comment]
Looks good, thank you!

**Pull request merged**
