### PR TITLE
[Fix] Layout shift when switching from sidebar gallery to floating style

### PR DESCRIPTION
**Pull request by ntshcalleia**

### CODE REVIEW

**Review by sambua — COMMENTED** [review]
Hi @ntshcalleia I think you add this line before related to the `sidebaroptions.aspectratio` to fix video container when sidebar is visible. And it was reason for shaking, I didn't remove it to fix shaking and applied different approach.

**Comment by ntshcalleia** [comment]
Hi @sambua, I'm not sure why,but unfortunately your PR didn't work for me or Sam. I checked the minified code and confirmed the latest changes were included, but I still had layout shifting issues due to changes to the aspect ratio when the player left in-article state

**Comment by sambua** [comment]
Hi @ntshcalleia , I was aware it was related to that changes, but tried to fix by left your changes. On that case we should remove that line at all, as it was related to the sidebar gallery, and now we're not using it.

**Comment by ntshcalleia** [comment]
Hi @sambua, I'm not sure what you mean, we're still using it. What I did was ensure the container keeps the correct aspect-ratio for the sidebar gallery even after it switches to floating state.

**Comment by sambua** [comment]
Hi @ntshcalleia I meant statement `!gallerySidebar && showsidebargallery` and using `sidebaroptions` which mean's it will be not applied to the gallery sidebar which was created for. I see you made changes on latest comments.

**Comment by ntshcalleia** [comment]
Hi @sambua, yes, that line only gets applied when the gallery sidebar isn't active so that the container remains with the correct aspect ratio even when we switch to floating. But I never removed the line where we're applying the aspect ratio on the element when the sidebar gallery is in view. You're mixing line 799 with 804, they are similar, but they do different things:
https://github.com/betajs/betajs-media-components/pull/465/files#diff-dd3d48531850fb2126c882db107548f133fa27992b32448acfd38e166221b0c7R799
https://github.com/betajs/betajs-media-components/pull/465/files#diff-dd3d48531850fb2126c882db107548f133fa27992b32448acfd38e166221b0c7R803

**Comment by sambua** [comment]
yep @ntshcalleia correct I've mixed lines, on that case will be better to give it different name, like `floatingoptions.aspectratio` to not confuse in the future and let us now why this code is applied. Or maybe `sidebaroptions.fallbackfloatingaspectratio`  

Also latest changes adding fullscreen also fix fullscreen related bug as well 👍

**Review by sambua — APPROVED** [review]
Works as expected, Well done! 👍

**Pull request merged**
